### ISSUE TITLE
Cannot find module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates'

### ISSUE THREAD

**Issue by j0k3r** [functionalone/serverless-iam-roles-per-function#1]
I just tried the plugin and got that error:

```
  Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-iam-roles-per-function" initialization errored: Cannot find module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates'
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.4.0
     Serverless Version:     1.26.0
```

I have defined it in my serverless.yml:

```yml
plugins:
    - serverless-webpack
    - serverless-pseudo-parameters
    - serverless-iam-roles-per-function

# ...

functions:
    api:
        handler: lambda.apiHandler
        iamRoleStatements:
            -
                Effect: 'Allow'
                Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DeleteNetworkInterface
                    - sns:Publish
                Resource: '*'
```
