### ISSUE TITLE
Adding disableLogs: true to lambda config makes plugin throw an error

### ISSUE THREAD

**Issue by markgibaud-vtail** [functionalone/serverless-iam-roles-per-function#102]
Hi there,

I have the following config in Serverless.yml for a lambda:

```
asyncSyncProductsDb:
    handler: functions/asyncSyncProductsDb/asyncSyncProductsDb.main
    timeout: 300
    memorySize: 2048
    events:
       //eventbridge event source
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameters
          - ses:SendEmail
        Resource:
          - '*'
```

Now I want to temporarily disable creation of the log group, in order to later re-enable & recreate it in a nested stack using `serverless-plugin-split-stacks` custom config. However when I add `disableLogs: true` [as per the docs](https://www.serverless.com/framework/docs/providers/aws/guide/functions#log-group-resources) I get an error:

```
asyncSyncProductsDb:
    handler: functions/asyncSyncProductsDb/asyncSyncProductsDb.main
    disableLogs: true
    timeout: 300
    memorySize: 2048
    events:
       //eventbridge event source
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameters
          - ses:SendEmail
        Resource:
          - '*'
```

```
Serverless Error ----------------------------------------

  serverless-iam-roles-per-function: ERROR: Function Resource is not in expected format. For function name: asyncSyncProductsDb
```

The plugin is throwing [this error](https://github.com/functionalone/serverless-iam-roles-per-function/blob/master/src/lib/index.ts#L186) even though my lambda config is fine.

If I comment out the `iamRoleStatements` then it works fine and deletes the log group, ostensibly because this plugin does  not process the lambda config.

Any ideas on fixes or workarounds? I need to do this to about 30 lambdas :-)
