### ISSUE TITLE
Is it possible to attach managed policy?

### ISSUE THREAD

**Issue by davorceman** [functionalone/serverless-iam-roles-per-function#114]
Is it possible to attach managed policies to roles created with this plugin?
I'm deploying rest of the stack with TF or CF, and I would like to create managed policy with correct permissions to these resources needed for these lambdasw  (Kinesis, DynamoDB, RDS...).
Then I should be able to attach these managed policies to roles per function created with this plugin.

Something similar is possible without plugin, using just aws provider, but this is for all functions. I would like to have it per function :)
```
iam:
    role:
      managedPolicies:
        - arn:aws:iam::123456789:policy/myPolicy1
        - arn:aws:iam::123456789:policy/myPolicy2
```
