### ISSUE TITLE
Conform to SLS v3 `iam` format?

### ISSUE THREAD

**Issue by henhal** [functionalone/serverless-iam-roles-per-function#125]
In earlier SLS versions, `iamRoleStatements` was the key used under `provider` to specify shared IAM role statements.
In this plugin, the same syntax is used to define statements per function.

In SLS v3, `iamRoleStatements` was replaced by

```
iam:
  role:
   statements:
```

Any thoughts on following this syntax also for the per-function directives, such as

```
functions:
  MyFunction:
    iam:
      role:
        statementsInherit: true
        statements:
          - Effect: Allow
          - Action: dynamodb:*
          - Resource: xxxx
```

to support the other IAM related functionality [now supported](https://www.serverless.com/framework/docs/providers/aws/guide/iam) on the provider level such as `managedPolicies`, `permissionsBoundary` etc?
