### ISSUE TITLE
Stack default policy not renamed

### ISSUE THREAD

**Issue by RafPe** [functionalone/serverless-iam-roles-per-function#14]
Hi, 

Great idea for plugin - however I'm having issue where default name role is used for the stack 

The following is what I got 
```
provider:
  name: aws
  runtime: nodejs8.10
  provider:
  region: eu-west-1
  iamRoleStatementsName: SLSCloudRole-dev-abc
```

Based on the above I would assume default role name created to be `SLSCloudRole-dev-abc` however I get `sls-stackname-dev-eu-west-1-lambdaRole`

Have tried also with the details below on `provider` level but result is the same   
```
    iamRoleStatementsName: SLSCloudRole-dev-abc
    iamRoleStatements: []
``` 

Any hints ?
