### ISSUE TITLE
self:custom: variables are not evaluated inside iamRoleStatements

### ISSUE THREAD

**Issue by onnimonni** [functionalone/serverless-iam-roles-per-function#15]
Given:
```yaml
custom:
  kmsKeyArn: "arn:aws:kms:${self:provider.region}:*:alias/my-application-${env:ENVIRONMENT}-kms"

functions:
  hello:
    handler: handler.hello
    events:
      - schedule: rate(1 minute)
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - kms:Decrypt
        Resource: "${self:custom:kmsKeyArn}"
```

Results in:
```
  An error occurred: HelloIamRoleLambdaExecution - Syntax errors in policy. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 13134b80-fd51-11e8-86e9-6f039a192bc0).
```

But If I use it directly works perfectly:
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - schedule: rate(1 minute)
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - kms:Decrypt
        Resource: "arn:aws:kms:${self:provider.region}:*:alias/my-application-${env:ENVIRONMENT}-kms"
```
