### ISSUE TITLE
Usage with split stacks?

### ISSUE THREAD

**Issue by btmdave** [functionalone/serverless-iam-roles-per-function#23]
Hello,

Any idea if this would conflict with [serverless-plugin-split-stacks](https://github.com/dougmoscrop/serverless-plugin-split-stacks)? I'm getting an error The following resource(s) failed to create: [MyFunctionIamRoleLambdaExecution].

This is using the following:

```
MyFunction:
 handler: index.handler
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'
```

Thank you
