### ISSUE TITLE
2.0.0 regression: ARN arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole is not valid

### ISSUE THREAD

**Issue by schmiddy** [functionalone/serverless-iam-roles-per-function#24]
Hi,

We started seeing a failure like this in one of our serverless deploys, which installs the latest `serverless-iam-roles-per-function` plugin as part of the deploy. The error went away when we pinned back to `1.0.4`, i.e. with `sls plugin install -n serverless-iam-roles-per-function@1.0.4`. Here's the error from the CloudFormation console:

> 11:42:18 UTC-0400    CREATE_FAILED    AWS::IAM::Role    DbDashoverflowDashguardIamRoleLambdaExecution    ARN arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole is not valid. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: InvalidInput; Request ID: 8777cbd2-...)

> Physical ID:Project-prod4-seq-over-guard

Our serverless template looks roughly like this (chunks of the template are redacted, but it seems to be enough to repro the issue):
```
---

service: 'Monitoring-${env:STACK_PREFIX}'

provider:
  name: aws
  runtime: python3.7

  stage: production
  region: ${env:AWS_DEFAULT_REGION}

custom:
  pythonRequirements:
    fileName: ../../requirements.txt
    dockerizePip: non-linux

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
functions:

  db-overflow-guard:
    handler: myfunc.lambda_handler
    memorySize: 256
    description: production monitoring
    timeout: 30
    environment:
      STACK_PREFIX: '${env:STACK_PREFIX}'

    vpc:
      subnetIds:
        - Fn::ImportValue: !Sub "${env:STACK_PREFIX}-PrivateSubnetOne"
        - Fn::ImportValue: !Sub "${env:STACK_PREFIX}-PrivateSubnetTwo"
      securityGroupIds:
        - Fn::GetAtt: ServerlessSecurityGroup.GroupId

    iamRoleStatementsInherit: true
    iamRoleStatementsName: ${env:STACK_PREFIX}-seq-over-guard
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "secretsmanager:GetSecretValue"
        Resource:
          - !Join
            - ':'
            - - "arn:aws:secretsmanager"
              - !Ref AWS::Region
              - !Ref AWS::AccountId
              - !Join
                - '/'
                - - "secret:Project/${env:STACK_PREFIX}"
                  - "DBPass*"

    events:
      - schedule: rate(12 hours)


# you can add CloudFormation resource templates here
resources:
  Description: Serverless functions for production monitoring

  Resources:

    ServerlessSecurityGroup:
      Type: 'AWS::EC2::SecurityGroup'
      Properties:
        GroupDescription: SG for Lambda, RDS will allow access
        VpcId:
          Fn::ImportValue: !Sub "${env:STACK_PREFIX}-VPC"
        Tags:
          - Key: Name
            Value: Security Group for Serverless Application

...
```
