### ISSUE TITLE
X-Ray integration removed

### ISSUE THREAD

**Issue by AndreaAdvanon** [functionalone/serverless-iam-roles-per-function#28]
```yml
service: service

provider:
  name: aws
  runtime: nodejs10.x
  tracing:
    lambda: true

plugins:
  - serverless-iam-roles-per-function

custom:
  serverless-iam-roles-per-function:
    defaultInherit: true

functions:
  a:
    handler: handler.a
  b:
    handler: handler.b
    iamRoleStatements:
      - Effect: Allow
        Action: some:Action
        Resource: someResource
```

function `a` will have `X-Ray` working as expected, but not function `b`
