### ISSUE TITLE
Overwrite the default naming convention

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [functionalone/serverless-iam-roles-per-function#34]
Rather than forcing the IAM role name to be `<service-name>-<stage>-<function-name>-<region>-lambdaRole`, can it be defined something like this?

```yaml
custom:
  serverless-iam-roles-per-function:
    iamRoleNamePrefix: prefix
    iamRoleNameSuffix: suffix
    # iam role name becomes `prefix-<function-name>-suffix`
```
