### ISSUE TITLE
Can't rename role name using iamRoleStatementsName

### ISSUE THREAD

**Issue by austinn0** [functionalone/serverless-iam-roles-per-function#38]
I use this in multiple modules, but for some reason it isn't working in a new module and I can't figure out why. Here's my serverless.yml file
```
service: 
  name: ${self:custom.provider.service}-device-notification-handler

plugins:
  - serverless-export-env
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-offline

package:
  individually: true
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.provider.regions.${self:custom.stage}}
  profile: ${self:custom.provider.profile}
  stage: dev

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  helloWorld:
    handler: src/hello.main
    iamRoleStatementsName: hello-world-lambdaRole
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:GetItem        
        Resource: "*"
```

And when I run it I get the following error:

> An error occurred: IamRoleLambdaExecution - 1 validation error detected: Value 'smartwater-device-notification-handler-dev-ca-central-1-lambdaRole' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64

And here's my package.json dependencies:

"serverless": "^1.60.4",
"serverless-iam-roles-per-function": "^2.0.2"
