### ISSUE TITLE
lambda {AWS::Region} and ARN regions

### ISSUE THREAD

**Issue by tgensol** [functionalone/serverless-iam-roles-per-function#4]
Hi,

I found an issue, or at least I got an issue. Let's say my functions are working in **us-east-1**, and I have a function with this : 

```
       iamRoleStatements:
         - Effect: "Allow"        
           Action:
             - lambda:InvokeFunction
           Resource: 
             - arn:aws:lambda:us-east-1:###
             - arn:aws:lambda:eu-west-1:###
```

The resources when doing serverless package or deploy, will become  :${AWS::Region}, and thus, my IAM ROLE will be able to invoke on Resource :

```
          - arn:aws:lambda:us-east-1:###
          - arn:aws:lambda:us-east-1:### 
```

It is then not working properly. How can I deal with this issue ? Do I miss a parameter or something ?
I had to roll back to the iamRoleStatements in my provider and stop using the plugin.

Thanks !

**Comment by tgensol** [comment]
I just found that it is doing the same if I use the classic iamRoleStatements in the main provider. Is It an serverless issue or we cannot do what I want to do ? (I was using before an role that I created manually)

**Comment by glicht** [comment]
Not sure I fully understand your issue. If you can provide reference to a simple demo project, I think it can help. Anyway, as it sounds like an issue which is also relevant for provider level statements, it is probably best to try to bring this up with the serverless framework.

**Comment by tgensol** [comment]
@glicht Thanks ! I will try to ask on the serverless community too, it is maybe a missunderstanding of myself : 

```
service: serverless-function

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  cfLogs: true

functions:
  post:
    handler: handler.post
    memorySize: 512
    timeout: 60
    iamRoleStatements:
         - Effect: "Allow"        
           Action:
             - lambda:InvokeFunction
           Resource: 
             - arn:aws:lambda:us-east-1:###
             - arn:aws:lambda:eu-west-1:###    
```

If I am using this code above or below : 


```
service: serverless-function

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: 
             - arn:aws:lambda:us-east-1:###
             - arn:aws:lambda:eu-west-1:###    
      Action:
        -  "lambda:InvokeFunction" 
```

Both the final ARN on the AWS IAM will become arn:aws:lambda:us-east-1:### and arn:aws:lambda:**us-east-1**:###   because the function is in the region **us-east-1**, how can we have ARNS from differents regions of the actual region of the function ? I can see that the cloud formation template automatically replace the regions with _**{AWS::Region}**_. But can we disable this ?

Thanks !
