### ISSUE TITLE
Just use iamRoleStatementsName

### ISSUE THREAD

**Issue by clarkd** [functionalone/serverless-iam-roles-per-function#40]
It it supported to just use the `iamRoleStatementsName` config and not customize the roles in any way?

**Comment by jacksgt** [comment]
Yes, you can definitely do the following:

```
  MyAwesomeFunction:
    handler: awesome.handler
    iamRoleStatementsName: "my-awesome-role-name"
    iamRoleStatements: []
```
