### ISSUE TITLE
No role gets created

### ISSUE THREAD

**Issue by jameswoodley** [functionalone/serverless-iam-roles-per-function#45]
I'm using the plugin as described, but no role gets created and I can't query my index...

I get no errors

```
functions:
  create-widget:
    handler: Moveable.Widget.Settings::Settings.Handler::CreateWidget
    package:
      artifact: bin/Release/netcoreapp3.1/settings.zip
    environment:
      SETTINGS_HASH_INDEX_NAME: ${file(../Infrastructure/database.yml):custom.settingsHashIndexName}
    events:
      - http:
          path: widgets
          method: post
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - 'Fn::Join':
              - '/'
              - 
                - 'Fn::ImportValue': ${self:provider.stage}-SettingsTable
                - '/index/IX_Hash'
```
