### ISSUE TITLE
Multiple resources in iamRoleStatements 

### ISSUE THREAD

**Issue by robertkaucher** [functionalone/serverless-iam-roles-per-function#48]
I want to ensure that a function is able to access two queues in SQS. I am not sure how to structure the YAML. I have tried the following, neither of which worked.

```
  v1_postEntitlement:
    handler: src/entitlements/v1_postEntitlement.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: 
          - arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:LicenseUpdateSerivce.fifo
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: 
          - arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:LoggingQueue
    events:
      - http:
          path: vw/v1/entitlement
          method: post
```

and..

```
  v1_postEntitlement:
    handler: src/entitlements/v1_postEntitlement.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: 
          - arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:LoggingQueue
          - arn:aws:sqs:us-east-1:xxxxxxxxxxxxxx:LicenseUpdateSerivce.fifo
    events:
      - http:
          path: vw/v1/entitlement
          method: post
```
