### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by cyberfox1** [functionalone/serverless-iam-roles-per-function#51]
All lambdas get a default role associated with stack rather than the custom one per lambda. Copied example code.

Using serverless 2.0.0.

**Comment by VMois** [comment]
Please, provide code here + version of the library.

**Comment by jfoxtech** [comment]
Allow me to provide an example:

Code snippet:

```
  events-buffered-topic-posts:
    handler: bin/events-buffered-topic-posts
    name: events-buffered-topic-posts-${opt:stage}
    description: "Call topic-post service when assets are done processing"
    package:
      exclude:
        - ./**
      include:
        - ./bin/events-buffered-topic-posts
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "lambda:InvokeFunction"
        Resource: [
          "arn:aws:lambda:us-east-1:655063978684:function:topic-post-service-${opt:stage}",
          "arn:aws:lambda:us-east-1:655063978684:function:buffer-service-${opt:stage}"
        ]
```

Output:

```
cd src/places/; serverless deploy --stage "jfox" --infraenv "dev" -v --force
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Configuration warning:
Serverless:   at 'functions['place-service']': unrecognized property 'iamRoleStatements'
Serverless:   at 'functions['place-stream']': unrecognized property 'iamRoleStatements'
Serverless:   at 'functions['place-data']': unrecognized property 'iamRoleStatements'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
```

Any help on this would be much appreciated.
