### ISSUE TITLE
DQL wrong SNS permissions while SQS resource set

### ISSUE THREAD

**Issue by Enase** [functionalone/serverless-iam-roles-per-function#59]
**Issue description:**
Plugin adds `sns:Publish` permission in case if function has `onError` definition and doesn't take into account that it might be SQS resource arn

Steps to reproduce:
1. Define any function with `onError` property mapped to SQS resource:
```
functions:
  function_name_here:
    handler: functions/function_name_here/index.handler
    iamRoleStatementsName: "function_name_here_lambda_role"
    iamRoleStatements:
      - ${file(../../function_name_here.yml)}
    onError:
      Fn::GetAtt: [QueueNameDeadLetterQueue, Arn]
```

2. Define SQS Resource:
```
Resources:
  QueueNameDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "SomeNameDeadLetterQueue"
```

3. Deploy your code with `sls deploy`

**Expected result:**
No useless permissions should be added

**Current result**
Useless permissions added:
```
        {
            "Action": [
                "sns:Publish"
            ],
            "Resource": "arn:aws:sqs:{region_here}:{accountId_here}:SomeNameDeadLetterQueue",
            "Effect": "Allow"
        }
```

**Background:**

Serverless added support for DQL setup with `onError` function property [here](https://github.com/serverless/serverless/pull/3609). However it has some [strange concurrency issue](https://www.serverless.com/framework/docs/providers/aws/guide/functions/#dead-letter-queue-dlq) described in docs. But still community has [some workarounds](https://github.com/serverless/serverless/issues/4647#issuecomment-474306379) and moreover, it's [hard to reproduce](https://github.com/serverless/serverless/issues/4647#issuecomment-454556417) it (that's why it's not fixed yet), so that most people (like me) use it as is without any issues.

**TBD**

As possible solution I recommend to delete [additional policy definitions](https://github.com/functionalone/serverless-iam-roles-per-function/blob/5bebde915ba1173a24df6f446022b2b6705bcde9/src/lib/index.ts#L251) in case if `onError` property set in function definition.

In case if we want to keep backward compatibility we may add configuration property like `addOnErrorPolicy: boolean`.
