### ISSUE TITLE
Configuration warning at 'functions.import': unrecognized property 'iamRoleStatementsInherit'

### ISSUE THREAD

**Issue by BartusZak** [functionalone/serverless-iam-roles-per-function#61]
```
> serverless deploy --verbose
Serverless: Configuration warning at 'functions.import': unrecognized property 'iamRoleStatementsInherit'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
```

```
serverless -v
Framework Core: 2.11.1
Plugin: 4.1.2
SDK: 2.3.2
Components: 3.3.0
```

```
  "devDependencies": {
    "serverless-iam-roles-per-function": "^2.0.2"
  },
```

_serverless.yml_
```
plugins:
  - serverless-iam-roles-per-function # Define IAM roles per function

...

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.IMPORTER_DYNAMODB_TABLE}"

...

functions:
  import:
    handler: handlers/import.handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - s3:GetObject
          - s3:PutObject 
        Resource:
          - Fn::Join:
            - ""
            - - !GetAtt ImporterS3Bucket.Arn
              - "/*"
```

**Comment by davidfells** [comment]
I am experiencing this issue as well, same versions across the board except SLS Components @3.4

**Comment by tcastelli** [comment]
experiencing the same issue even with latests 3.0.0 version

**Comment by wujekbogdan** [comment]
The same applies to `iamRoleStatements`. I'm getting the following error:

```
Configuration warning at 'functions.postConfirmation': unrecognized property 'iamRoleStatements'
```

My config:
``` yml
functions:
  postConfirmation:
    handler: src/cognito-hooks/post-confirmation.handler
    events:
      - cognitoUserPool:
          pool: ${env:AWS_COGNITO_USER_POOL}
          trigger: PostConfirmation
          existing: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminUpdateUserAttributes
        Resource: arn:aws:cognito-idp:*:*:*
```

serverless version: `2.13.0`

**Comment by glicht** [comment]
@BartusZak @tcastelli @davidfells @wujekbogdan can you try using version 3.0.1. Installing it by running:
```
npm install --save-dev serverless-iam-roles-per-function@next
```
It contains the a fix #63 from @Enase which may help

**Comment by BartusZak** [comment]
Thanks @glicht. 

Warnings disappeared.

**Comment by mdrijwan** [comment]
`npm install --save-dev serverless-iam-roles-per-function@next` worked out for me!

**Comment by prachi24cross7** [comment]
the npm install serverless-iam-per-function@next solved one issue, but throwing 

Serverless: Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements" 

error now

**Comment by Enase** [comment]
@prachi24cross7 It's expected behaviour. Serverless informs you that  `iamRoleStatements` won't be supported in version 3.

In order to fix it replace:

```
provider:
   iamRoleStatements
        - your statements here
```
with

```
provider:
  iam:
    role:
      statements:
        - your statements here
```
