### ISSUE TITLE
Add Ability to Reference Existing Roles

### ISSUE THREAD

**Issue by sam-mundle** [functionalone/serverless-iam-roles-per-function#66]
The title pretty much says it all. Would be great because we maintain all of our roles in a separate system and we want to keep our serverless.yml as short as possible

**Comment by ricardo-lino** [comment]
I think you don't need this plugin, You can use the role property to define an existing role: 

Ex: 
```yaml
some:
  handler: index.someHandler
  role: arn...role/myrole #arn of a role that already exists
```

for more information: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-role
