### ISSUE TITLE
iamGlobalPermissionsBoundary is required, but not read

### ISSUE THREAD

**Issue by excenter** [functionalone/serverless-iam-roles-per-function#72]
```
  Error: schema is invalid: data.properties['custom'].properties['serverless-iam-roles-per-function'].properties['iamGlobalPermissionsBoundary'] should be object,boolean
```

function definition
```
functions:
  add_tabs:
    handler: handler.add_tabs
    description: add tabs to an existing template
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - ssm:GetParameters
        Resource: 'arn:aws:ssm:${self:provider.region}:*:product/${self:provider.stage}*'

```
using sls framework 1.8.3, plugin v3.1.0

I attempted to fill in this to quell the error, but to no avail. 
```
custom:
  serverless-iam-roles-per-function:
    iamGlobalPermissionsBoundary: false

```
